# Generated by Django 4.1.6 on 2023-02-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_orig_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="orig_name",),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
    ]
